name: Elixir CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: 22.2
          elixir-version: 1.9.4

      - name: Install dependencies
        run: mix deps.get

      - name: Check mix format
        run: mix format --check-formatted

      - name: Run tests
        run: mix test
